#ifndef DEF_PHONEMANAGER_MENUICONS_H
#define DEF_PHONEMANAGER_MENUICONS_H

//PhoneManager
#define MNI_PHONEMANAGER_CALL                      "phonemanagerCall"
#define MNI_PHONEMANAGER_CALL_IN                   "phonemanagerCallIn"
#define MNI_PHONEMANAGER_CALL_OUT                  "phonemanagerCallOut"
#define MNI_PHONEMANAGER_CALL_ERROR                "phonemanagerCallError"
#define MNI_PHONEMANAGER_NUMBER_APPEND             "phonemanagerNumberAppend"
#define MNI_PHONEMANAGER_NUMBER_REMOVE             "phonemanagerNumberRemove"
#define MNI_PHONEMANAGER_NUMBER_SAVE               "phonemanagerNumberSave"
#define MNI_PHONEMANAGER_NUMBER_CANCEL             "phonemanagerNumberCancel"
#define MNI_PHONEMANAGER_BACKGROUND                "phonemanagerBackground"
#define MNI_PHONEMANAGER_BUTTON_HOVER              "phonemanagerButtonHover"
#define MNI_PHONEMANAGER_BUTTON_PRESSED            "phonemanagerButtonPressed"
#define MNI_PHONEMANAGER_BUTTON_ACCEPT             "phonemanagerButtonAccept"
#define MNI_PHONEMANAGER_BUTTON_ACCEPT_HOVER       "phonemanagerButtonAcceptHover"
#define MNI_PHONEMANAGER_BUTTON_ACCEPT_PRESSED     "phonemanagerButtonAcceptPressed"
#define MNI_PHONEMANAGER_BUTTON_REJECT             "phonemanagerButtonReject"
#define MNI_PHONEMANAGER_BUTTON_REJECT_HOVER       "phonemanagerButtonRejectHover"
#define MNI_PHONEMANAGER_BUTTON_REJECT_PRESSED     "phonemanagerButtonRejectPressed"
#define MNI_PHONEMANAGER_VOLUME_HANDLE             "phonemanagerVolumeHandle"
#define MNI_PHONEMANAGER_VIDEO_CALL                "phonemanagerVideoCall"
#define MNI_PHONEMANAGER_VIDEO_RESIZE              "phonemanagerVideoResize"
#define MNI_PHONEMANAGER_VIDEO_WAIT                "phonemanagerVideoWait"
#define MNI_PHONEMANAGER_CALL_TIMER                "phonemanagerCallTimer"
#define MNI_PHONEMANAGER_CALL_ANSWER               "phonemanagerCallAnswer"
#define MNI_PHONEMANAGER_CALL_REJECT               "phonemanagerCallReject"
#define MNI_PHONEMANAGER_CALL_HANGUP               "phonemanagerCallHangup"
#define MNI_PHONEMANAGER_DIALER_DIALOG             "phonemanagerDialerDialog"
#define MNI_PHONEMANAGER_DIALER_1                  "phonemanagerDialer1"
#define MNI_PHONEMANAGER_DIALER_2                  "phonemanagerDialer2"
#define MNI_PHONEMANAGER_DIALER_3                  "phonemanagerDialer3"
#define MNI_PHONEMANAGER_DIALER_4                  "phonemanagerDialer4"
#define MNI_PHONEMANAGER_DIALER_5                  "phonemanagerDialer5"
#define MNI_PHONEMANAGER_DIALER_6                  "phonemanagerDialer6"
#define MNI_PHONEMANAGER_DIALER_7                  "phonemanagerDialer7"
#define MNI_PHONEMANAGER_DIALER_8                  "phonemanagerDialer8"
#define MNI_PHONEMANAGER_DIALER_9                  "phonemanagerDialer9"
#define MNI_PHONEMANAGER_DIALER_10                 "phonemanagerDialer10"
#define MNI_PHONEMANAGER_DIALER_11                 "phonemanagerDialer11"
#define MNI_PHONEMANAGER_DIALER_12                 "phonemanagerDialer12"
#define MNI_PHONEMANAGER_CALLHISTORTY_CLEAR        "phonemanagerCallHistoryClear"
#define MNI_PHONEMANAGER_DIALER_ENABLED            "phonemanagerDialerEnabled"
#define MNI_PHONEMANAGER_DIALER_DISABLED           "phonemanagerDialerDisabled"
#define MNI_PHONEMANAGER_CAMERA_ENABLED            "phonemanagerCameraEnabled"
#define MNI_PHONEMANAGER_CAMERA_DISABLED           "phonemanagerCameraDisabled"
#define MNI_PHONEMANAGER_MICROPHONE_ENABLED        "phonemanagerMicrophoneEnabled"
#define MNI_PHONEMANAGER_MICROPHONE_DISABLED       "phonemanagerMicrophoneDisabled"
#define MNI_PHONEMANAGER_VIDEOPREVIEW_ENABLED      "phonemanagerVideoPreviewEnabled"
#define MNI_PHONEMANAGER_VIDEOPREVIEW_DISABLED     "phonemanagerVideoPreviewDisabled"

#endif // DEF_PHONEMANAGER_MENUICONS_H
