#ifndef DEF_PHONEMANAGER_MESSAGECHATWINDOWWIDGETS_H
#define DEF_PHONEMANAGER_MESSAGECHATWINDOWWIDGETS_H

#define MCWW_PHONEMANAGER_CALL             300
#define MCWW_PHONEMANAGER_CALL_HANDLE      310
#define MCWW_PHONEMANAGER_EDITNUMBERS      650

#endif // DEF_PHONEMANAGER_MESSAGECHATWINDOWWIDGETS_H
