#ifndef DEF_PHONEMANAGER_NOTIFICATIONTYPES_H
#define DEF_PHONEMANAGER_NOTIFICATIONTYPES_H

#define NNT_PHONEMANAGER_MISSEDCALL   "PhoneManagerMissedCall"

#endif // DEF_PHONEMANAGER_NOTIFICATIONTYPES_H
