#ifndef DEF_PHONEMANAGER_NOTIFICATIONTYPEORDERS_H
#define DEF_PHONEMANAGER_NOTIFICATIONTYPEORDERS_H

#define NTO_PHONEMANAGER_MISSEDCALL            100

#endif //  DEF_PHONEMANAGER_NOTIFICATIONTYPEORDERS_H
