#ifndef DEF_PHONEMANAGER_OPTIONWIDGETORDERS_H
#define DEF_PHONEMANAGER_OPTIONWIDGETORDERS_H

//None = ON_PHONEMANAGER_SIPPHONE
#define OWO_PHONEMANAGER_SIPPHONE                500

#endif //DEF_PHONEMANAGER_OPTIONWIDGETORDERS_H
