#ifndef DEF_PHONEMANAGER_OPTIONWIDGETORDERS_H
#define DEF_PHONEMANAGER_OPTIONWIDGETORDERS_H

//None = ON_PHONEMANAGER_SIPPHONE
#define OHO_PHONEMANAGER_SIP_ACCOUNT                100
#define   OWO_PHONEMANAGER_SIP_LOGIN                110
#define   OWO_PHONEMANAGER_SIP_PASSWORD             120
#define OHO_PHONEMANAGER_SIP_CONNECTION             300
#define   OWO_PHONEMANAGER_SIP_SERVER               310
#define   OWO_PHONEMANAGER_SIP_PROXY                320
#define OHO_PHONEMANAGER_SIP_MEDIA                  500
#define   OWO_PHONEMANAGER_SIP_STUNSERVER           510
#define   OWO_PHONEMANAGER_SIP_ICEENABLED           520

#endif //DEF_PHONEMANAGER_OPTIONWIDGETORDERS_H
